language: elixir
notifications:
  recipients:
    - eduardo@gurgel.me
elixir:
  - 1.0.0
  - 1.0.1
  - 1.0.2
otp_release:
  - 17.0
  - 17.1
sudo: false
install: mix deps.get
before_install: mix local.hex --force
script: mix test --no-start
